### ISSUE TITLE
Allow running without letsencrypt

### ISSUE THREAD

**Issue by robert-m-johnson** [adi90x/rancher-active-proxy#12]
According to the docs, the minimal command required to run the container is
`docker run -d -p 80:80 adi90x/rancher-active-proxy`

Using a slightly modified version of the command to run interactively and use a fixed version number,
`docker run -p 80:80 adi90x/rancher-active-proxy:v0.8.6`
I get the error
`Error: can't access to '/etc/letsencrypt' directory !
Check that '/etc/letsencrypt' directory is declared has a writable volume.`

Ideally the container should be able to run in the absence of any letsencrypt configuration as per the documentation.

**Comment by adi90x** [comment]
hello ,
If you want to run it interactively you can just delete the command with /bin/bash.

So for example you can start it with : `docker run -p 80:80 adi90x/rancher-active-proxy:v0.8.6 /bin/bash`
This will overwrite the default command ( forego start -r ) .
Tell me if everything is working fine like this ?

**Comment by adi90x** [comment]
@robert-m-johnson  I got your problem ! 
In fact, you are right /etc/letsencrypt folder was missing if you start RAP with no directory mount leading to an error ! 
It was corrected and push to tag v0.9.1 or latest ! 
Thanks for using RAP and for the feedback !

**Comment by adi90x** [comment]
Do not hesitate to confirm if it is working now !

**Comment by robert-m-johnson** [comment]
Thanks so much for sorting this so quickly! I can confirm I no longer get the error when using v0.9.1.

**Comment by robert-m-johnson** [comment]
Ah, sadly I now get a different error when trying to run the container. Here is my `docker-compose.yml`:

```
version: '2'
services:
  active-proxy:
    image: adi90x/rancher-active-proxy:v0.9.1
```

Here are the container logs:
```
26/01/2017 13:31:38level=info msg="Starting rancher-gen RAP Edition master (c5670c9aeedfee7ba00b63d1dd996b271e7249d9)"
26/01/2017 13:31:38level=info msg="Initializing Rancher Metadata client (version latest)"
26/01/2017 13:31:38level=info msg="Processing all templates once."
26/01/2017 13:31:38level=info msg="All templates processed. Exiting."
26/01/2017 13:31:38/app/entrypoint.sh: line 42: LETSENCRYPT_CONTAINERS[@]: unbound variable
```

**Comment by adi90x** [comment]
Right, I think it is because you don't have any service setup with a rap.host label.
I will add a check to disable this part of the script if there is nothing to create !

**Comment by adi90x** [comment]
Hello, 

Just push tag v0.9.2 that should solve the problem !

**Comment by robert-m-johnson** [comment]
Still have the same error I'm afraid :(

![image](https://cloud.githubusercontent.com/assets/17594209/22339215/1e1bf244-e3e1-11e6-949c-303c23e42fbd.png)

```
26/01/2017 16:04:45level=info msg="Starting rancher-gen RAP Edition master (c5670c9aeedfee7ba00b63d1dd996b271e7249d9)"
26/01/2017 16:04:45level=info msg="Initializing Rancher Metadata client (version latest)"
26/01/2017 16:04:45level=info msg="Processing all templates once."
26/01/2017 16:04:45level=info msg="All templates processed. Exiting."
26/01/2017 16:04:45/app/entrypoint.sh: line 44: LETSENCRYPT_CONTAINERS[@]: unbound variable
```

**Comment by adi90x** [comment]
Do you have any service with a rap.le_host or rap.host label set ?

**Comment by adi90x** [comment]
Just add another check on whether config is empty or not ( you can re pull v0.9.2 in a few minutes when it is completly build ! )  Should be ok now ! 
However, I think this check should also be add to the LE script that is run every time config is updated or you will probably go for the same kind of problem on any config change ! 
I will look into that tonight !

**Comment by patsissons** [comment]
`v0.9.2` is still broken (same issue with the `unbound variable`). I had to revert back to `v0.8.5` (and bind a dummy volume for let's encrypt) to get things working again.

**Comment by adi90x** [comment]
@patsissons I working on this ! 
In fact, there is probably 2 or 3 lines to change all over RAP !

**Comment by patsissons** [comment]
i'll watch this issue and pin my container to `v0.8.5` until you close this out.

**Comment by adi90x** [comment]
OK I update version v0.9.2 with new changes ! 
Image is rebuilding on DockerHub and it should be good ( I just setup an empty VPS with only rancher and RAP started and it work with no problem ! 

@robert-m-johnson @patsissons  Do not hesitate to retry v0.9.2 image version and report any other problems !
